apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../base/argo-apps/clickhouse-helm.yaml
  - ../../../base/argo-apps/ingress-apisix-helm.yaml
  - ../../../base/argo-apps/kafka-helm.yaml
  - ../../../base/argo-apps/linkerd-helm.yaml
  - ../../../base/argo-apps/redpanda-helm.yaml

